CREATE DATABASE firmat IF NOT EXISTS;

USE firmat;

CREATE TABLE usuarios (
	id INT NOT NULL AUTO_INCREMENT PRIMARY_KEY,
	nombre VARCHAR (255) NOT NULL,
	usuario VARCHAR(50) NOT NULL,
	contraseña VARCHAR (255) NOT NULL
);